import { Wllama } from "@wllama/wllama/esm/index.js";

export interface GGUFModelOption {
  id: string;
  name: string;
  repo: string;
  file: string;
  size: string;
  description: string;
  quant: string;
}

export const PRESET_GGUF_MODELS: GGUFModelOption[] = [
  {
    id: "slimezu-slack",
    name: "Slack GGUF (slimezu/Slack)",
    repo: "slimezu/Slack",
    file: "Slack.gguf",
    quant: "imatrix",
    size: "1.46 GB",
    description:
      "Slack GGUF running locally in the browser through WebAssembly."
  }
];

export type ModelLoadStatus =
  | "idle"
  | "downloading"
  | "loading"
  | "ready"
  | "error";

class LocalGGUFEngine {
  private wllama: Wllama | null = null;
  private initPromise: Promise<boolean> | null = null;

  public status: ModelLoadStatus = "idle";
  public downloadProgress = 0;
  public statusMessage = "";

  private readonly MODEL_URL =
    "https://huggingface.co/slimezu/Slack/resolve/main/Slack.gguf";

  public isReady(): boolean {
    return (
      this.status === "ready" &&
      this.wllama !== null &&
      this.wllama.isModelLoaded()
    );
  }

  private async getOrCreateWllama(): Promise<Wllama> {
    if (this.wllama) {
      return this.wllama;
    }

    this.wllama = new Wllama({
      default: "/wllama.wasm",
      "single-thread/wllama.wasm": "/wllama.wasm",
      "multi-thread/wllama.wasm": "/wllama.wasm"
    });

    return this.wllama;
  }

  public async initEngine(
    model: GGUFModelOption = PRESET_GGUF_MODELS[0],
    onProgress?: (progress: number, message: string) => void
  ): Promise<boolean> {
    if (this.initPromise) {
      return this.initPromise;
    }

    this.initPromise = (async () => {
      try {
        if (this.isReady()) {
          onProgress?.(
            100,
            "Slack GGUF is already loaded in WebAssembly memory."
          );
          return true;
        }

        this.status = "loading";
        this.statusMessage = "Initializing WebAssembly...";
        onProgress?.(5, this.statusMessage);

        const instance = await this.getOrCreateWllama();

        if (instance.isModelLoaded()) {
          this.status = "ready";
          this.statusMessage = "Slack GGUF is ready.";
          onProgress?.(100, this.statusMessage);
          return true;
        }

        this.status = "downloading";
        this.statusMessage = "Downloading Slack GGUF from Hugging Face...";
        onProgress?.(10, this.statusMessage);

        const progressCallback = ({
          loaded,
          total
        }: {
          loaded: number;
          total: number;
        }) => {
          const percent =
            total > 0 ? Math.round((loaded / total) * 100) : 0;

          this.downloadProgress = percent;
          this.statusMessage =
            `Downloading Slack.gguf: ${percent}% ` +
            `(${(loaded / 1024 / 1024).toFixed(0)} MB / ` +
            `${(total / 1024 / 1024).toFixed(0)} MB)`;

          onProgress?.(percent, this.statusMessage);
        };

        this.status = "loading";
        this.statusMessage = "Loading Slack GGUF into WebAssembly memory...";
        onProgress?.(15, this.statusMessage);

        await instance.loadModelFromUrl(this.MODEL_URL, {
          progressCallback,

          // Context window
          n_ctx: 1024,

          // Browser CPU threads
          n_threads: 2,

          // Batch size
          n_batch: 256
        });

        this.status = "ready";
        this.statusMessage =
          "Active: Slack GGUF (local WebAssembly engine)";

        onProgress?.(100, this.statusMessage);

        return true;
      } catch (err: any) {
        console.error("Failed to load Slack GGUF:", err);

        this.status = "error";

        const message = err?.message || String(err);

        this.statusMessage =
          `Slack GGUF failed to load: ${message}`;

        onProgress?.(0, this.statusMessage);

        return false;
      } finally {
        this.initPromise = null;
      }
    })();

    return this.initPromise;
  }

  public async generateChatCompletion(
    messages: Array<{
      role: "system" | "user" | "assistant";
      content: string;
    }>,
    onToken?: (token: string) => void
  ): Promise<string> {
    if (!this.wllama || !this.wllama.isModelLoaded()) {
      throw new Error(
        "Slack GGUF is not loaded. Initialize the model first."
      );
    }

    try {
      const response = await this.wllama.createChatCompletion({
        messages: messages.map((message) => ({
          role: message.role,
          content: message.content
        })),

        max_tokens: 512,
        temperature: 0.3,
        stream: false
      });

      const result =
        response?.choices?.[0]?.message?.content?.trim() || "";

      if (result) {
        onToken?.(result);
      }

      return result || "No response generated by Slack GGUF.";
    } catch (err: any) {
      console.error("Slack GGUF inference error:", err);

      throw new Error(
        `Slack GGUF inference error: ${err?.message || err}`
      );
    }
  }

  public async unload(): Promise<void> {
    if (this.wllama) {
      try {
        await this.wllama.exit();
      } catch (_) {}
    }

    this.wllama = null;
    this.status = "idle";
    this.downloadProgress = 0;
    this.statusMessage = "";
  }
}

export const ggufEngine = new LocalGGUFEngine();
